### ISSUE TITLE
Cannot learn Dragonscale leatherworking specialization as alliance Shaman

### ISSUE THREAD

**Issue by Zhaamon** [chromiecraft/chromiecraft#3769]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

![image](https://user-images.githubusercontent.com/63854803/178485665-82fde6b1-5974-4fcc-83f1-36e199caf341.png)
I'm trying to learn dragonscale leatherworking as a Draenei Shamman.
I'm level 52, LW level 275 which should be enough I believe.
My cursor turns to a skill book, but all I get is regular dialog.
On wowhead, the quest seems to be locked to rogue and hunter for alliance, as there were no shammans.
Link to quest: https://classic.wowhead.com/quest=5141/dragonscale-leatherworking

### Expected Blizzlike Behaviour

I should (I think) be able to learn dragonscale leatherworking as an ally draenei shaman as long as I meet the requirements.

### Source

https://classic.wowhead.com/npc=7866/peter-galen

### Steps to reproduce the problem

1. Get an alliance Draenei shaman lvl 52, and LW level 275
2. Talk to NPC https://classic.wowhead.com/npc=7866/peter-galen while having no other LW specialization learned
3. If the same happens, he only has a regular text display.

### Extra Notes

NPC - https://classic.wowhead.com/npc=7866/peter-galen
QUEST - https://classic.wowhead.com/quest=5141/dragonscale-leatherworking

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

Using Reccount

### Server

ChromieCraft

**Comment by pangolp** [comment]
Hello, good evening. I have not been able to reproduce the problem on my development server, which is using the latest version of the emulator. However, that doesn't mean, that it can't become a problem inside the ChromieCraft server. On my development server, I have not implemented the level limitations, nor the progression system. It could also be a bug, which has already been fixed by the community. In contraction, I leave the images of the tests that I made.

![WoWScrnShot_071522_223937](https://user-images.githubusercontent.com/2810187/179330431-0311a2d4-b2c7-4710-abe8-7e15cb961e59.jpg)

![WoWScrnShot_071522_223919](https://user-images.githubusercontent.com/2810187/179330534-df5edc0a-085c-49ea-a858-2a433feae6ed.jpg)

![WoWScrnShot_071522_223909](https://user-images.githubusercontent.com/2810187/179330524-248edce2-ab88-4587-aa4b-b4fe37fc84aa.jpg)

In tbc's wowhead, there is already a mention of the shaman, as you mentioned, that was missing in classic.
- https://tbc.wowhead.com/quest=5141/dragonscale-leatherworking

**Comment by Zhaamon** [comment]
Hi!
I tested again with the client downloaded from the website, no addons, and the bug is still present at the moment.

**Comment by pangolp** [comment]
> Hi! I tested again with the client downloaded from the website, no addons, and the bug is still present at the moment.

Possibly, the change was applied in the emulator, but not yet uploaded to ChromieCraft. However, it is likely that when the server is updated, it will be reflected. That must be the reason why it works for me and not for you. Just wait for the server to inform about an update and then we will try again.

**Comment by pangolp** [comment]
Hello, good morning. I just tested in the test realm, and the npc, allows me to take the quest, being level 52 shaman as you indicated and having the profession in 225 skill.

![WoWScrnShot_071822_064200](https://user-images.githubusercontent.com/2810187/179485719-edd4a1d3-ccb5-4e3f-9c0a-c27593bb951c.jpg)

**Comment by Zhaamon** [comment]
I'm extremely sorry for wasting everyone's time, I was on a spec quest from before I stopped playing for a few months and didn't really remember it, I did check the quest log but somehow missed it before.
Once again, extremely sorry for wasting everyone's time.

**Comment by pangolp** [comment]
> I'm extremely sorry for wasting everyone's time, I was on a spec quest from before I stopped playing for a few months and didn't really remember it, I did check the quest log but somehow missed it before.
> Once again, extremely sorry for wasting everyone's time.

The mission of the server and the emulator is to provide a better place for everyone. Don't feel sorry for being wrong. We all make mistakes. So keep reporting, because we need more feedback from the community.
